repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile=black']
        files: ^app/
        exclude: /migrations/

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        files: ^app/
        exclude: /migrations/

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ['--config=app/.flake8']
        files: ^app/
        exclude: /migrations/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        files: ^app/
        exclude: /(migrations|tests)/
        args: ['--config-file=mypy.ini']
